CREATE DATABASE bamboo CHARACTER SET UTF8MB4;

CREATE TABLE boards (
	id INT PRIMARY KEY AUTO_INCREMENT
	, title VARCHAR(50) NOT NULL
	, content VARCHAR(1000) NOT NULL
	, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	, delete_flg TINYINT(1) NOT NULL DEFAULT '0'
	, delete_at TIMESTAMP NULL
);

ALTER TABLE boards MODIFY COLUMN create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;